module.exports.tableData = [
    {
        classname: 'ban',
        speak: 'bàn',
        properties: [
            { name: 'ID_BAN', type: 'int', speak: 'id bàn', isNull: false },
            { name: 'TEN', type: 'string', speak: 'tên bàn', isNull: true },
            { name: 'GHI_CHU', type: 'int', speak: 'ghi chú', isNull: true },
        ],
        keys: ['ID_BAN'],
    },
    {
        classname: 'cthd',
        speak: 'chi tiết hóa đơn',
        properties: [
            { name: 'ID_HOA_DON', type: 'int', speak: 'id hóa đơn', isNull: false },
            { name: 'ID_SAN_PHAM', type: 'int', speak: 'id sản phẩm', isNull: false },
            { name: 'SO_LUONG', type: 'int', speak: 'số lượng', isNull: false },
            { name: 'DON_GIA', type: 'int', speak: 'đơn giá', isNull: false },
            { name: 'DIEM_TICH_LUY', type: 'int', speak: 'điểm tích lũy', isNull: false },
        ],
        keys: ['ID_HOA_DON', 'ID_SAN_PHAM'],
    },
    {
        classname: 'ctkm',
        speak: 'chi tiết khuyến mãi',
        properties: [
            { name: 'ID_KHUYEN_MAI', type: 'int', speak: 'id khuyến mãi', isNull: false },
            { name: 'ID_SAN_PHAM', type: 'int', speak: 'id sản phẩm', isNull: false },
            { name: 'SO_LUONG', type: 'int', speak: 'số lượng', isNull: false },
            { name: 'DON_GIA', type: 'int', speak: 'đơn giá', isNull: true },
            { name: 'DIEM_TICH_LUY', type: 'int', speak: 'điểm tích lũy', isNull: true },
        ],
        keys: ['ID_KHUYEN_MAI', 'ID_SAN_PHAM'],
    },
    {
        classname: 'dat_ban',
        speak: 'đặt bàn',
        properties: [
            { name: 'ID_KHACH_HANG', type: 'int', speak: 'id khách hàng ', isNull: false },
            { name: 'ID_BAN', type: 'int', speak: 'id bàn', isNull: false },
            { name: 'THOI_GIAN_LAP', type: 'datetime', speak: 'thời gian lập', isNull: false },
            { name: 'THOI_GIAN_NHAN', type: 'datetime', speak: 'thời gian nhận', isNull: true },
            { name: 'GHI_CHU', type: 'string', speak: 'ghi chú', isNull: true },
        ],
        keys: ['username', 'ID_BAN', 'ID_KHACH_HANG', 'THOI_GIAN_LAP'],
    },
    {
        classname: 'hoa_don',
        speak: 'hóa đơn',
        properties: [
            { name: 'ID_HOA_DON', type: 'int', speak: 'id hóa đơn', isNull: false },
            { name: 'ID_KHACH_HANG', type: 'int', speak: 'id khách hàng', isNull: true },
            { name: 'ID_BAN', type: 'int', speak: 'id bàn', isNull: true },
            { name: 'ID_NHAN_VIEN', type: 'int', speak: 'id nhân viên', isNull: true },
            { name: 'THOI_GIAN_LAP', type: 'datetime', speak: 'thời gian', isNull: false },
        ],
        keys: ['ID_HOA_DON'],
    },
    {
        classname: 'thanh_toan_hoa_don',
        speak: 'thanh toán hóa đơn',
        properties: [
            { name: 'ID_HOA_DON', type: 'int', speak: 'id hóa đơn', isNull: false },
            { name: 'ID_TAI_KHOAN_THANH_TOAN', type: 'int', speak: 'id tài khoản thanh toán', isNull: false },
            { name: 'THOI_GIAN_THANH_TOAN', type: 'datetime', speak: 'thời gian thanh toán', isNull: false },
            { name: 'PHAN_TRAM_TICH_LUY', type: 'float', speak: 'phần trăm tích lũy', isNull: false },
            { name: 'SO_LUONG_DIEM_DOI', type: 'int', speak: 'số lượng điểm đổi', isNull: false },
            { name: 'TY_GIA_DIEM_DOI', type: 'float', speak: 'tỷ giá quy đổi', isNull: false },
        ],
        keys: ['ID_HOA_DON', 'ID_TAI_KHOAN_THANH_TOAN', 'THOI_GIAN_THANH_TOAN'],
    },
    {
        classname: 'khach_hang',
        speak: 'khách hàng',
        properties: [
            { name: 'ID_KHACH_HANG', type: 'int', speak: 'id khách hàng', isNull: false },
            { name: 'TEN', type: 'string', speak: 'tên', isNull: false },
            { name: 'SDT', type: 'string', speak: 'số điện thoại', isNull: false },
            { name: 'ID_TAI_KHOAN', type: 'int', speak: 'id tài khoản', isNull: true },
            { name: 'DIEM_TICH_LUY', type: 'int', speak: 'điểm tích lũy', isNull: false },
            { name: 'EMAIL', type: 'text', speak: 'email', isNull: true },
            { name: 'GOOGLE', type: 'text', speak: 'google', isNull: true },
            { name: 'FACEBOOK', type: 'text', speak: 'facebook', isNull: true },
        ],
        keys: ['ID_KHACH_HANG'],
    },
    {
        classname: 'khuyen_mai',
        speak: 'khuyến mãi',
        properties: [
            { name: 'ID_KHUYEN_MAI', type: 'int', speak: 'id khuyến mãi', isNull: false },
            { name: 'TEN', type: 'string', speak: 'tên', isNull: false },
            { name: 'THOI_GIAN_DIEN_RA', type: 'datetime', speak: 'thời gian diễn ra', isNull: false },
            { name: 'THOI_GIAN_KET_THUC', type: 'datetime', speak: 'thời gian kết thúc', isNull: false },
        ],
        keys: ['ID_KHUYEN_MAI'],
    },
    {
        classname: 'loai_san_pham',
        speak: 'loại sản phẩm',
        properties: [
            { name: 'ID_LOAI_SAN_PHAM', type: 'int', speak: 'id loại sản phẩm', isNull: false },
            { name: 'TEN', type: 'string', speak: 'tên', isNull: false },
            { name: 'LINK_ANH', type: 'string', speak: 'link ảnh', isNull: true },
            { name: 'GHI_CHU', type: 'string', speak: 'ghi chú', isNull: true },
        ],
        keys: ['ID_LOAI_SAN_PHAM'],
    },
    {
        classname: 'nhan_vien',
        speak: 'nhân viên',
        properties: [
            { name: 'ID_NHAN_VIEN', type: 'int', speak: 'id nhân viên', isNull: false },
            { name: 'TEN', type: 'string', speak: 'tên', isNull: false },
            { name: 'SDT', type: 'string', speak: 'số điện thoại', isNull: false },
            { name: 'LOAI', type: 'int', speak: 'loại', isNull: false },
            { name: 'ID_TAI_KHOAN', type: 'int', speak: 'id tài khoản', isNull: false },
            { name: 'NGAY_SINH', type: 'date', speak: 'ngày sinh', isNull: false },
            { name: 'LINK_ANH', type: 'text', speak: 'link ảnh', isNull: true },
            { name: 'EMAIL', type: 'text', speak: 'email', isNull: true },
        ],
        keys: ['ID_NHAN_VIEN'],
    },
    {
        classname: 'san_pham',
        speak: 'sản phẩm',
        properties: [
            { name: 'ID_SAN_PHAM', type: 'int', speak: 'id sản phẩm', isNull: false },
            { name: 'ID_LOAI_SAN_PHAM', type: 'int', speak: 'id loại sản phẩm', isNull: false },
            { name: 'TEN', type: 'string', speak: 'tên', isNull: false },
            { name: 'GIA', type: 'int', speak: 'giá', isNull: false },
            { name: 'DIEM_TICH_LUY', type: 'int', speak: 'điểm tích lũy', isNull: false },
            { name: 'GHI_CHU', type: 'string', speak: 'ghi chú', isNull: true },
            { name: 'LINK_ANH', type: 'string', speak: 'link ảnh', isNull: false },
        ],
        keys: ['ID_SAN_PHAM'],
    },
    {
        classname: 'tai_khoan',
        speak: 'tài khoản',
        properties: [
            { name: 'ID_TAI_KHOAN', type: 'int', speak: 'id tài khoản', isNull: false },
            { name: 'USERNAME', type: 'string', speak: 'tên đăng nhập', isNull: false },
            { name: 'PASSWORD', type: 'string', speak: 'mật khẩu', isNull: false },
            { name: 'LOAI', type: 'int', speak: 'loại', isNull: false },
        ],
        keys: ['ID_TAI_KHOAN'],
    },
];
